### ISSUE TITLE
Music Control Via Notification

### ISSUE THREAD

**Issue by Pra-San** [ContriHUB/Music-Player#3]
Another way to implement media controls would be to integrate media controls into the notification shade. This would allow users to control playback (play/pause, skip, rewind, etc.) without needing to open the app, providing convenient access to controls while the app runs in the background.
This feature improves user convenience by making music controls available directly in the notification shade, even when the app is minimized.
The media controls should include basic actions like play/pause, next/previous track, and should display additional details like the current track title and artist. For enhanced user experience, album art and a progress bar should be displayed in the notification. The notification should be persistent and should function seamlessly while the app is playing music in the background.
**!! Fix this issue before attempting #5 !!**

**Comment by nxd010** [comment]
Hello @Pra-San Sir! I was trying to implement the given function, but I'll have to implement the Background Play issue since the app doesn't support it properly. Can you please look into it since its already another issue? 
Background music plays as long the activity_play_song.xml is served when the app goes back to the main page background music stops and this feature can only be implemented when that issue is resolved!

**Comment by Pra-San** [comment]
Yes that's a challenge to solve, you will be given extra points if you can solve that.@nxd010

**Comment by Pra-San** [comment]
@nxd010  I have made a new issue for this #5 .Hope that helps

**Comment by RITIK-CHAUDHRY** [comment]
is this issue open??

**Comment by Pra-San** [comment]
@RITIK-CHAUDHRY Take a look at issue 5 first
